[2018-05-23T16:17:54.527] [ERROR] error - { method: 'POST',
  url: '/api/login',
  body: { username: '17602004746', password: 'wokaopy123' },
  costTime: undefined,
  err: 
   TypeError: resLogger.info is not a function
       at Object.resLogger (/Users/spfv/blog/server/utils/log.js:56:15)
       at app.use (/Users/spfv/blog/server/server.js:21:10)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) }
[2018-05-23T16:17:56.471] [ERROR] error - { method: 'POST',
  url: '/api/login',
  body: { username: '17602004746', password: 'wokaopy123' },
  costTime: undefined,
  err: 
   TypeError: resLogger.info is not a function
       at Object.resLogger (/Users/spfv/blog/server/utils/log.js:56:15)
       at app.use (/Users/spfv/blog/server/server.js:21:10)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) }
[2018-05-23T16:18:38.371] [ERROR] error - { method: 'POST',
  url: '/api/login',
  body: { username: '17602004746', password: 'wokaopy123' },
  costTime: undefined,
  err: 
   TypeError: resLogger.info is not a function
       at Object.resLogger (/Users/spfv/blog/server/utils/log.js:56:15)
       at app.use (/Users/spfv/blog/server/server.js:21:10)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) }
[2018-05-23T16:48:11.013] [ERROR] error - { method: 'POST',
  url: '/api/login',
  body: { username: '17602004746', password: 'wokaopy123' },
  costTime: undefined,
  err: 
   TypeError: resLogger.info is not a function
       at resLogger (/Users/spfv/blog/server/utils/log.js:56:15)
       at app.use (/Users/spfv/blog/server/server.js:23:3)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) }
[2018-05-23T17:37:32.594] [ERROR] error - { method: 'POST',
  url: '/api/deleteArticle',
  body: { data: { id: '5afd315ee53b923d4cd09252' } },
  costTime: undefined,
  err: 
   ReferenceError: doc is not defined
       at deleteArticle (/Users/spfv/blog/server/info/article.js:126:15)
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at next (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
       at module.exports (/Users/spfv/blog/server/token/checkToken.js:16:9)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) }
[2018-05-23T17:39:13.421] [ERROR] error - { method: 'POST',
  url: '/api/deleteArticle',
  body: { data: { id: '5afd315ee53b923d4cd09252' } },
  costTime: undefined,
  err: 
   ReferenceError: doc is not defined
       at deleteArticle (/Users/spfv/blog/server/info/article.js:127:15)
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at next (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
       at module.exports (/Users/spfv/blog/server/token/checkToken.js:16:9)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) }
[2018-05-23T17:53:12.330] [ERROR] error - { method: 'POST',
  url: '/api/deleteArticle',
  body: { id: '5afbe8362f36f2a985b2fd00' },
  costTime: undefined,
  err: 
   ReferenceError: doc is not defined
       at deleteArticle (/Users/spfv/blog/server/info/article.js:127:15)
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at next (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
       at module.exports (/Users/spfv/blog/server/token/checkToken.js:16:9)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) }
[2018-05-24T10:49:26.603] [ERROR] error - { method: 'POST',
  url: '/api/postArticleContent',
  body: { id: '5afd315ee53b923d4cd09252' },
  costTime: undefined,
  err: 
   { ForbiddenError: has not article
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at postArticleContent (/Users/spfv/blog/server/info/article.js:71:14)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'has not article' } }
[2018-05-24T10:50:06.540] [ERROR] error - { method: 'POST',
  url: '/api/postArticleContent',
  body: { id: '5afa9c4eec988955bcf0efc2' },
  costTime: undefined,
  err: 
   { ForbiddenError: has not article
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at postArticleContent (/Users/spfv/blog/server/info/article.js:71:14)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'has not article' } }
[2018-05-24T10:50:07.202] [ERROR] error - { method: 'POST',
  url: '/api/postArticleContent',
  body: { id: '5afd315ee53b923d4cd09252' },
  costTime: undefined,
  err: 
   { ForbiddenError: has not article
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at postArticleContent (/Users/spfv/blog/server/info/article.js:71:14)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'has not article' } }
[2018-05-24T10:50:07.950] [ERROR] error - { method: 'POST',
  url: '/api/postArticleContent',
  body: { id: '5b03c91904f97674c3c1989d' },
  costTime: undefined,
  err: 
   { ForbiddenError: has not article
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at postArticleContent (/Users/spfv/blog/server/info/article.js:71:14)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'has not article' } }
[2018-05-24T10:50:08.643] [ERROR] error - { method: 'POST',
  url: '/api/postArticleContent',
  body: { id: '5afd315ee53b923d4cd09252' },
  costTime: undefined,
  err: 
   { ForbiddenError: has not article
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at postArticleContent (/Users/spfv/blog/server/info/article.js:71:14)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'has not article' } }
[2018-05-24T10:50:12.705] [ERROR] error - { method: 'POST',
  url: '/api/postArticleContent',
  body: { id: '5afa9c4eec988955bcf0efc2' },
  costTime: undefined,
  err: 
   { ForbiddenError: has not article
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at postArticleContent (/Users/spfv/blog/server/info/article.js:71:14)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'has not article' } }
[2018-05-24T10:50:13.268] [ERROR] error - { method: 'POST',
  url: '/api/postArticleContent',
  body: { id: '5afd315ee53b923d4cd09252' },
  costTime: undefined,
  err: 
   { ForbiddenError: has not article
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at postArticleContent (/Users/spfv/blog/server/info/article.js:71:14)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'has not article' } }
[2018-05-24T10:50:13.773] [ERROR] error - { method: 'POST',
  url: '/api/postArticleContent',
  body: { id: '5b03c91904f97674c3c1989d' },
  costTime: undefined,
  err: 
   { ForbiddenError: has not article
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at postArticleContent (/Users/spfv/blog/server/info/article.js:71:14)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'has not article' } }
[2018-05-24T10:50:19.445] [ERROR] error - { method: 'POST',
  url: '/api/postArticleContent',
  body: { id: '5afd315ee53b923d4cd09252' },
  costTime: undefined,
  err: 
   { ForbiddenError: has not article
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at postArticleContent (/Users/spfv/blog/server/info/article.js:71:14)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'has not article' } }
[2018-05-24T10:50:24.122] [ERROR] error - { method: 'POST',
  url: '/api/postArticleContent',
  body: { id: '5b03c91904f97674c3c1989d' },
  costTime: undefined,
  err: 
   { ForbiddenError: has not article
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at postArticleContent (/Users/spfv/blog/server/info/article.js:71:14)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'has not article' } }
[2018-05-24T10:50:26.263] [ERROR] error - { method: 'POST',
  url: '/api/postArticleContent',
  body: { id: '5afa9c4eec988955bcf0efc2' },
  costTime: undefined,
  err: 
   { ForbiddenError: has not article
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at postArticleContent (/Users/spfv/blog/server/info/article.js:71:14)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'has not article' } }
[2018-05-24T10:50:52.703] [ERROR] error - { method: 'POST',
  url: '/api/postArticleContent',
  body: { id: '5afd315ee53b923d4cd09252' },
  costTime: undefined,
  err: 
   { ForbiddenError: has not article
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at postArticleContent (/Users/spfv/blog/server/info/article.js:72:14)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'has not article' } }
[2018-05-24T10:52:08.892] [ERROR] error - { method: 'POST',
  url: '/api/postArticleContent',
  body: { id: 112 },
  costTime: undefined,
  err: 
   TypeError: Cannot read property 'length' of null
       at postArticleContent (/Users/spfv/blog/server/info/article.js:66:11)
       at <anonymous> }
[2018-05-24T10:52:43.811] [ERROR] error - { method: 'POST',
  url: '/api/postArticleContent',
  body: { id: 112 },
  costTime: undefined,
  err: 
   { ForbiddenError: has not article
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at postArticleContent (/Users/spfv/blog/server/info/article.js:71:14)
       at <anonymous> message: 'has not article' } }
[2018-05-24T17:15:38.721] [ERROR] error - { method: 'POST',
  url: '/api/upArticle',
  body: 
   { id: '5b0650f4c49497637f151765',
     title: '新标题',
     creatTime: '2018-05-24 13:43',
     content: ' ' },
  costTime: undefined,
  err: 
   ReferenceError: Uparticle is not defined
       at upArticle (/Users/spfv/blog/server/info/article.js:106:19)
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at next (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
       at module.exports (/Users/spfv/blog/server/token/checkToken.js:16:9)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) }
[2018-05-24T17:40:43.654] [ERROR] error - { method: 'POST',
  url: '/api/upArticle',
  body: 
   { id: '5b0650f4c49497637f151765',
     title: '新标题',
     creatTime: '2018-05-24 13:43',
     content: ' ' },
  costTime: undefined,
  err: 
   ReferenceError: mongoose is not defined
       at upArticle (/Users/spfv/blog/server/info/article.js:100:29)
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at next (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
       at module.exports (/Users/spfv/blog/server/token/checkToken.js:16:9)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) }
[2018-05-29T14:33:47.749] [ERROR] error - { method: 'POST',
  url: '/api/downArticle',
  body: { id: '' },
  costTime: undefined,
  err: 
   Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
       at new ObjectID (/Users/spfv/blog/node_modules/bson/lib/bson/objectid.js:51:11)
       at ObjectID [as ObjectId] (/Users/spfv/blog/node_modules/bson/lib/bson/objectid.js:32:43)
       at upArticle (/Users/spfv/blog/server/info/article.js:107:25)
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at next (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
       at module.exports (/Users/spfv/blog/server/token/checkToken.js:16:9)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) }
[2018-05-29T14:34:32.402] [ERROR] error - { method: 'POST',
  url: '/api/downArticle',
  body: { id: '5b0cf35b2d6da768558dfd94' },
  costTime: undefined,
  err: 
   { MongoError: E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId('5b0cf35b2d6da768558dfd94') }
       at /Users/spfv/blog/node_modules/mongodb/lib/bulk/unordered.js:535:15
       at handleCallback (/Users/spfv/blog/node_modules/mongodb/lib/utils.js:128:55)
       at resultHandler (/Users/spfv/blog/node_modules/mongodb/lib/bulk/unordered.js:456:5)
       at /Users/spfv/blog/node_modules/mongodb-core/lib/connection/pool.js:541:18
       at _combinedTickCallback (internal/process/next_tick.js:131:7)
       at process._tickCallback (internal/process/next_tick.js:180:9)
     name: 'BulkWriteError',
     message: 'E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId(\'5b0cf35b2d6da768558dfd94\') }',
     driver: true,
     code: 11000,
     index: 0,
     errmsg: 'E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId(\'5b0cf35b2d6da768558dfd94\') }',
     getOperation: [Function],
     toJSON: [Function],
     toString: [Function],
     result: 
      BulkWriteResult {
        ok: [Getter],
        nInserted: [Getter],
        nUpserted: [Getter],
        nMatched: [Getter],
        nModified: [Getter],
        nRemoved: [Getter],
        getInsertedIds: [Function],
        getUpsertedIds: [Function],
        getUpsertedIdAt: [Function],
        getRawResponse: [Function],
        hasWriteErrors: [Function],
        getWriteErrorCount: [Function],
        getWriteErrorAt: [Function],
        getWriteErrors: [Function],
        getLastOp: [Function],
        getWriteConcernError: [Function],
        toJSON: [Function],
        toString: [Function],
        isOk: [Function] } } }
[2018-05-29T14:34:54.992] [ERROR] error - { method: 'POST',
  url: '/api/downArticle',
  body: { id: '5b0cf35b2d6da768558dfd94' },
  costTime: undefined,
  err: 
   { MongoError: E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId('5b0cf35b2d6da768558dfd94') }
       at /Users/spfv/blog/node_modules/mongodb/lib/bulk/unordered.js:535:15
       at handleCallback (/Users/spfv/blog/node_modules/mongodb/lib/utils.js:128:55)
       at resultHandler (/Users/spfv/blog/node_modules/mongodb/lib/bulk/unordered.js:456:5)
       at /Users/spfv/blog/node_modules/mongodb-core/lib/connection/pool.js:541:18
       at _combinedTickCallback (internal/process/next_tick.js:131:7)
       at process._tickCallback (internal/process/next_tick.js:180:9)
     name: 'BulkWriteError',
     message: 'E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId(\'5b0cf35b2d6da768558dfd94\') }',
     driver: true,
     code: 11000,
     index: 0,
     errmsg: 'E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId(\'5b0cf35b2d6da768558dfd94\') }',
     getOperation: [Function],
     toJSON: [Function],
     toString: [Function],
     result: 
      BulkWriteResult {
        ok: [Getter],
        nInserted: [Getter],
        nUpserted: [Getter],
        nMatched: [Getter],
        nModified: [Getter],
        nRemoved: [Getter],
        getInsertedIds: [Function],
        getUpsertedIds: [Function],
        getUpsertedIdAt: [Function],
        getRawResponse: [Function],
        hasWriteErrors: [Function],
        getWriteErrorCount: [Function],
        getWriteErrorAt: [Function],
        getWriteErrors: [Function],
        getLastOp: [Function],
        getWriteConcernError: [Function],
        toJSON: [Function],
        toString: [Function],
        isOk: [Function] } } }
[2018-05-29T14:34:58.331] [ERROR] error - { method: 'POST',
  url: '/api/downArticle',
  body: { id: '5b0cf35b2d6da768558dfd94' },
  costTime: undefined,
  err: 
   { MongoError: E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId('5b0cf35b2d6da768558dfd94') }
       at /Users/spfv/blog/node_modules/mongodb/lib/bulk/unordered.js:535:15
       at handleCallback (/Users/spfv/blog/node_modules/mongodb/lib/utils.js:128:55)
       at resultHandler (/Users/spfv/blog/node_modules/mongodb/lib/bulk/unordered.js:456:5)
       at /Users/spfv/blog/node_modules/mongodb-core/lib/connection/pool.js:541:18
       at _combinedTickCallback (internal/process/next_tick.js:131:7)
       at process._tickCallback (internal/process/next_tick.js:180:9)
     name: 'BulkWriteError',
     message: 'E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId(\'5b0cf35b2d6da768558dfd94\') }',
     driver: true,
     code: 11000,
     index: 0,
     errmsg: 'E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId(\'5b0cf35b2d6da768558dfd94\') }',
     getOperation: [Function],
     toJSON: [Function],
     toString: [Function],
     result: 
      BulkWriteResult {
        ok: [Getter],
        nInserted: [Getter],
        nUpserted: [Getter],
        nMatched: [Getter],
        nModified: [Getter],
        nRemoved: [Getter],
        getInsertedIds: [Function],
        getUpsertedIds: [Function],
        getUpsertedIdAt: [Function],
        getRawResponse: [Function],
        hasWriteErrors: [Function],
        getWriteErrorCount: [Function],
        getWriteErrorAt: [Function],
        getWriteErrors: [Function],
        getLastOp: [Function],
        getWriteConcernError: [Function],
        toJSON: [Function],
        toString: [Function],
        isOk: [Function] } } }
[2018-05-29T14:36:19.684] [ERROR] error - { method: 'POST',
  url: '/api/downArticle',
  body: { id: '5b0cf35b2d6da768558dfd94' },
  costTime: undefined,
  err: 
   { MongoError: E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId('5b0cf35b2d6da768558dfd94') }
       at /Users/spfv/blog/node_modules/mongodb/lib/bulk/unordered.js:535:15
       at handleCallback (/Users/spfv/blog/node_modules/mongodb/lib/utils.js:128:55)
       at resultHandler (/Users/spfv/blog/node_modules/mongodb/lib/bulk/unordered.js:456:5)
       at /Users/spfv/blog/node_modules/mongodb-core/lib/connection/pool.js:541:18
       at _combinedTickCallback (internal/process/next_tick.js:131:7)
       at process._tickCallback (internal/process/next_tick.js:180:9)
     name: 'BulkWriteError',
     message: 'E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId(\'5b0cf35b2d6da768558dfd94\') }',
     driver: true,
     code: 11000,
     index: 0,
     errmsg: 'E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId(\'5b0cf35b2d6da768558dfd94\') }',
     getOperation: [Function],
     toJSON: [Function],
     toString: [Function],
     result: 
      BulkWriteResult {
        ok: [Getter],
        nInserted: [Getter],
        nUpserted: [Getter],
        nMatched: [Getter],
        nModified: [Getter],
        nRemoved: [Getter],
        getInsertedIds: [Function],
        getUpsertedIds: [Function],
        getUpsertedIdAt: [Function],
        getRawResponse: [Function],
        hasWriteErrors: [Function],
        getWriteErrorCount: [Function],
        getWriteErrorAt: [Function],
        getWriteErrors: [Function],
        getLastOp: [Function],
        getWriteConcernError: [Function],
        toJSON: [Function],
        toString: [Function],
        isOk: [Function] } } }
[2018-05-29T14:37:38.160] [ERROR] error - { method: 'POST',
  url: '/api/downArticle',
  body: { id: '5b0cf4e72d6da768558dfd95' },
  costTime: undefined,
  err: 
   { MongoError: E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId('5b0cf4e72d6da768558dfd95') }
       at /Users/spfv/blog/node_modules/mongodb/lib/bulk/unordered.js:535:15
       at handleCallback (/Users/spfv/blog/node_modules/mongodb/lib/utils.js:128:55)
       at resultHandler (/Users/spfv/blog/node_modules/mongodb/lib/bulk/unordered.js:456:5)
       at /Users/spfv/blog/node_modules/mongodb-core/lib/connection/pool.js:541:18
       at _combinedTickCallback (internal/process/next_tick.js:131:7)
       at process._tickCallback (internal/process/next_tick.js:180:9)
     name: 'BulkWriteError',
     message: 'E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId(\'5b0cf4e72d6da768558dfd95\') }',
     driver: true,
     code: 11000,
     index: 0,
     errmsg: 'E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId(\'5b0cf4e72d6da768558dfd95\') }',
     getOperation: [Function],
     toJSON: [Function],
     toString: [Function],
     result: 
      BulkWriteResult {
        ok: [Getter],
        nInserted: [Getter],
        nUpserted: [Getter],
        nMatched: [Getter],
        nModified: [Getter],
        nRemoved: [Getter],
        getInsertedIds: [Function],
        getUpsertedIds: [Function],
        getUpsertedIdAt: [Function],
        getRawResponse: [Function],
        hasWriteErrors: [Function],
        getWriteErrorCount: [Function],
        getWriteErrorAt: [Function],
        getWriteErrors: [Function],
        getLastOp: [Function],
        getWriteConcernError: [Function],
        toJSON: [Function],
        toString: [Function],
        isOk: [Function] } } }
[2018-06-01T10:39:00.450] [ERROR] error - { method: 'POST',
  url: '/api/upArticle',
  body: { id: '', title: '', creatTime: '', content: '' },
  costTime: undefined,
  err: 
   Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
       at new ObjectID (/Users/spfv/blog/node_modules/bson/lib/bson/objectid.js:51:11)
       at ObjectID [as ObjectId] (/Users/spfv/blog/node_modules/bson/lib/bson/objectid.js:32:43)
       at upArticle (/Users/spfv/blog/server/info/article.js:107:25)
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at next (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
       at module.exports (/Users/spfv/blog/server/token/checkToken.js:16:9)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) }
[2018-06-01T10:41:39.111] [ERROR] error - { method: 'POST',
  url: '/api/downArticle',
  body: { id: '5b10b18b81d48eb98c91acd6' },
  costTime: undefined,
  err: 
   Error: non-error thrown: "is not online"
       at Object.onerror (/Users/spfv/blog/node_modules/koa/lib/context.js:109:40)
       at onerror (/Users/spfv/blog/node_modules/koa/lib/application.js:147:32)
       at <anonymous> }
[2018-06-01T10:43:43.403] [ERROR] error - { method: 'POST',
  url: '/api/downArticle',
  body: { id: '5b10b18b81d48eb98c91acd6' },
  costTime: undefined,
  err: 
   { ForbiddenError: is not online
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at downArticle (/Users/spfv/blog/server/info/article.js:171:14)
       at <anonymous> message: 'is not online' } }
[2018-06-01T10:45:04.325] [ERROR] error - { method: 'POST',
  url: '/api/downArticle',
  body: { id: '5b10b18b81d48eb98c91acd6' },
  costTime: undefined,
  err: 
   { ForbiddenError: 文章没有下线
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at downArticle (/Users/spfv/blog/server/info/article.js:171:14)
       at <anonymous> message: '文章没有下线' } }
[2018-06-01T16:25:46.239] [ERROR] error - { method: 'GET',
  url: '/api/getArticleList',
  body: {},
  costTime: undefined,
  err: 
   { UnauthorizedError: token lose
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at module.exports (/Users/spfv/blog/server/token/checkToken.js:13:14)
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at next (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
       at /Users/spfv/blog/node_modules/koa-router/lib/router.js:346:16
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at /Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
       at dispatch (/Users/spfv/blog/node_modules/koa-router/lib/router.js:351:31)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at app.use (/Users/spfv/blog/server/server.js:21:9)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at bodyParser (/Users/spfv/blog/node_modules/koa-bodyparser/index.js:86:11)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'token lose' } }
[2018-06-01T16:26:05.127] [ERROR] error - { method: 'GET',
  url: '/api/getArticleList',
  body: {},
  costTime: undefined,
  err: 
   { UnauthorizedError: token lose
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at module.exports (/Users/spfv/blog/server/token/checkToken.js:13:14)
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at next (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
       at /Users/spfv/blog/node_modules/koa-router/lib/router.js:346:16
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at /Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
       at dispatch (/Users/spfv/blog/node_modules/koa-router/lib/router.js:351:31)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at app.use (/Users/spfv/blog/server/server.js:21:9)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at bodyParser (/Users/spfv/blog/node_modules/koa-bodyparser/index.js:86:11)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'token lose' } }
[2018-06-01T16:26:14.269] [ERROR] error - { method: 'GET',
  url: '/api/getArticleList',
  body: {},
  costTime: undefined,
  err: 
   { UnauthorizedError: token lose
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at module.exports (/Users/spfv/blog/server/token/checkToken.js:13:14)
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at next (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
       at /Users/spfv/blog/node_modules/koa-router/lib/router.js:346:16
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at /Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
       at dispatch (/Users/spfv/blog/node_modules/koa-router/lib/router.js:351:31)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at app.use (/Users/spfv/blog/server/server.js:21:9)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at bodyParser (/Users/spfv/blog/node_modules/koa-bodyparser/index.js:86:11)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'token lose' } }
[2018-06-01T16:26:51.869] [ERROR] error - { method: 'GET',
  url: '/api/getArticleList',
  body: {},
  costTime: undefined,
  err: 
   { UnauthorizedError: token lose
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at module.exports (/Users/spfv/blog/server/token/checkToken.js:13:14)
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at next (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
       at /Users/spfv/blog/node_modules/koa-router/lib/router.js:346:16
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at /Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
       at dispatch (/Users/spfv/blog/node_modules/koa-router/lib/router.js:351:31)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at app.use (/Users/spfv/blog/server/server.js:21:9)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at bodyParser (/Users/spfv/blog/node_modules/koa-bodyparser/index.js:86:11)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'token lose' } }
[2018-06-02T11:44:55.317] [ERROR] error - { method: 'POST',
  url: '/api/upArticle',
  body: 
   { id: '5b10b18b81d48eb98c91acd6',
     title: '新标题123',
     creatTime: '2018-06-01 10:38',
     content: '> 使用koa::: hljs-cente\n# 一级标题\n```\nconsole.log(data)\nttttt\n112\n``',
     htmlCode: '' },
  costTime: undefined,
  err: 
   { MongoError: E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId('5b10b18b81d48eb98c91acd6') }
       at /Users/spfv/blog/node_modules/mongodb/lib/bulk/unordered.js:535:15
       at handleCallback (/Users/spfv/blog/node_modules/mongodb/lib/utils.js:128:55)
       at resultHandler (/Users/spfv/blog/node_modules/mongodb/lib/bulk/unordered.js:456:5)
       at /Users/spfv/blog/node_modules/mongodb-core/lib/connection/pool.js:541:18
       at _combinedTickCallback (internal/process/next_tick.js:131:7)
       at process._tickCallback (internal/process/next_tick.js:180:9)
     name: 'BulkWriteError',
     message: 'E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId(\'5b10b18b81d48eb98c91acd6\') }',
     driver: true,
     code: 11000,
     index: 0,
     errmsg: 'E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId(\'5b10b18b81d48eb98c91acd6\') }',
     getOperation: [Function],
     toJSON: [Function],
     toString: [Function],
     result: 
      BulkWriteResult {
        ok: [Getter],
        nInserted: [Getter],
        nUpserted: [Getter],
        nMatched: [Getter],
        nModified: [Getter],
        nRemoved: [Getter],
        getInsertedIds: [Function],
        getUpsertedIds: [Function],
        getUpsertedIdAt: [Function],
        getRawResponse: [Function],
        hasWriteErrors: [Function],
        getWriteErrorCount: [Function],
        getWriteErrorAt: [Function],
        getWriteErrors: [Function],
        getLastOp: [Function],
        getWriteConcernError: [Function],
        toJSON: [Function],
        toString: [Function],
        isOk: [Function] } } }
[2018-06-02T11:45:08.982] [ERROR] error - { method: 'POST',
  url: '/api/upArticle',
  body: 
   { id: '5b10b18b81d48eb98c91acd6',
     title: '新标题123',
     creatTime: '2018-06-01 10:38',
     content: '> 使用koa::: hljs-cente\n# 一级标题\n```\nconsole.log(data)\nttttt\n112\n``',
     htmlCode: '' },
  costTime: undefined,
  err: 
   { MongoError: E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId('5b10b18b81d48eb98c91acd6') }
       at /Users/spfv/blog/node_modules/mongodb/lib/bulk/unordered.js:535:15
       at handleCallback (/Users/spfv/blog/node_modules/mongodb/lib/utils.js:128:55)
       at resultHandler (/Users/spfv/blog/node_modules/mongodb/lib/bulk/unordered.js:456:5)
       at /Users/spfv/blog/node_modules/mongodb-core/lib/connection/pool.js:541:18
       at _combinedTickCallback (internal/process/next_tick.js:131:7)
       at process._tickCallback (internal/process/next_tick.js:180:9)
     name: 'BulkWriteError',
     message: 'E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId(\'5b10b18b81d48eb98c91acd6\') }',
     driver: true,
     code: 11000,
     index: 0,
     errmsg: 'E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId(\'5b10b18b81d48eb98c91acd6\') }',
     getOperation: [Function],
     toJSON: [Function],
     toString: [Function],
     result: 
      BulkWriteResult {
        ok: [Getter],
        nInserted: [Getter],
        nUpserted: [Getter],
        nMatched: [Getter],
        nModified: [Getter],
        nRemoved: [Getter],
        getInsertedIds: [Function],
        getUpsertedIds: [Function],
        getUpsertedIdAt: [Function],
        getRawResponse: [Function],
        hasWriteErrors: [Function],
        getWriteErrorCount: [Function],
        getWriteErrorAt: [Function],
        getWriteErrors: [Function],
        getLastOp: [Function],
        getWriteConcernError: [Function],
        toJSON: [Function],
        toString: [Function],
        isOk: [Function] } } }
[2018-06-02T11:46:07.651] [ERROR] error - { method: 'POST',
  url: '/api/upArticle',
  body: 
   { id: '5b1211bdddf31d8a36a1f4ff',
     title: '新标题',
     creatTime: '2018-06-02 11:40',
     content: '12312312# 12321321',
     htmlCode: '<p>12312312# 12321321</p>\n' },
  costTime: undefined,
  err: 
   { MongoError: E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId('5b1211bdddf31d8a36a1f4ff') }
       at /Users/spfv/blog/node_modules/mongodb/lib/bulk/unordered.js:535:15
       at handleCallback (/Users/spfv/blog/node_modules/mongodb/lib/utils.js:128:55)
       at resultHandler (/Users/spfv/blog/node_modules/mongodb/lib/bulk/unordered.js:456:5)
       at /Users/spfv/blog/node_modules/mongodb-core/lib/connection/pool.js:541:18
       at _combinedTickCallback (internal/process/next_tick.js:131:7)
       at process._tickCallback (internal/process/next_tick.js:180:9)
     name: 'BulkWriteError',
     message: 'E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId(\'5b1211bdddf31d8a36a1f4ff\') }',
     driver: true,
     code: 11000,
     index: 0,
     errmsg: 'E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId(\'5b1211bdddf31d8a36a1f4ff\') }',
     getOperation: [Function],
     toJSON: [Function],
     toString: [Function],
     result: 
      BulkWriteResult {
        ok: [Getter],
        nInserted: [Getter],
        nUpserted: [Getter],
        nMatched: [Getter],
        nModified: [Getter],
        nRemoved: [Getter],
        getInsertedIds: [Function],
        getUpsertedIds: [Function],
        getUpsertedIdAt: [Function],
        getRawResponse: [Function],
        hasWriteErrors: [Function],
        getWriteErrorCount: [Function],
        getWriteErrorAt: [Function],
        getWriteErrors: [Function],
        getLastOp: [Function],
        getWriteConcernError: [Function],
        toJSON: [Function],
        toString: [Function],
        isOk: [Function] } } }
[2018-06-04T16:48:16.328] [ERROR] error - { method: 'GET',
  url: '/api/getArticleList',
  body: {},
  costTime: undefined,
  err: 
   { UnauthorizedError: token lose
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at module.exports (/Users/spfv/blog/server/token/checkToken.js:13:14)
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at next (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
       at /Users/spfv/blog/node_modules/koa-router/lib/router.js:346:16
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at /Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
       at dispatch (/Users/spfv/blog/node_modules/koa-router/lib/router.js:351:31)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at app.use (/Users/spfv/blog/server/server.js:21:9)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at bodyParser (/Users/spfv/blog/node_modules/koa-bodyparser/index.js:86:11)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'token lose' } }
[2018-06-04T16:48:18.324] [ERROR] error - { method: 'POST',
  url: '/api/postArticleContent',
  body: { id: '5b14fcd111fac960d136a71d' },
  costTime: undefined,
  err: 
   { UnauthorizedError: token lose
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at module.exports (/Users/spfv/blog/server/token/checkToken.js:13:14)
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at next (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
       at /Users/spfv/blog/node_modules/koa-router/lib/router.js:346:16
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at /Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
       at dispatch (/Users/spfv/blog/node_modules/koa-router/lib/router.js:351:31)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at app.use (/Users/spfv/blog/server/server.js:21:9)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at bodyParser (/Users/spfv/blog/node_modules/koa-bodyparser/index.js:86:11)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'token lose' } }
[2018-06-04T16:48:20.762] [ERROR] error - { method: 'POST',
  url: '/api/postArticleContent',
  body: { id: '5b14fcd111fac960d136a71d' },
  costTime: undefined,
  err: 
   { UnauthorizedError: token lose
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at module.exports (/Users/spfv/blog/server/token/checkToken.js:13:14)
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at next (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
       at /Users/spfv/blog/node_modules/koa-router/lib/router.js:346:16
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at /Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
       at dispatch (/Users/spfv/blog/node_modules/koa-router/lib/router.js:351:31)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at app.use (/Users/spfv/blog/server/server.js:21:9)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at bodyParser (/Users/spfv/blog/node_modules/koa-bodyparser/index.js:86:11)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'token lose' } }
[2018-06-04T16:48:21.995] [ERROR] error - { method: 'POST',
  url: '/api/postArticleContent',
  body: { id: '5b14fcd111fac960d136a71d' },
  costTime: undefined,
  err: 
   { UnauthorizedError: token lose
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at module.exports (/Users/spfv/blog/server/token/checkToken.js:13:14)
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at next (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
       at /Users/spfv/blog/node_modules/koa-router/lib/router.js:346:16
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at /Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
       at dispatch (/Users/spfv/blog/node_modules/koa-router/lib/router.js:351:31)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at app.use (/Users/spfv/blog/server/server.js:21:9)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at bodyParser (/Users/spfv/blog/node_modules/koa-bodyparser/index.js:86:11)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'token lose' } }
[2018-06-04T16:48:24.192] [ERROR] error - { method: 'POST',
  url: '/api/postArticleContent',
  body: { id: '5b14fcd111fac960d136a71d' },
  costTime: undefined,
  err: 
   { UnauthorizedError: token lose
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at module.exports (/Users/spfv/blog/server/token/checkToken.js:13:14)
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at next (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
       at /Users/spfv/blog/node_modules/koa-router/lib/router.js:346:16
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at /Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
       at dispatch (/Users/spfv/blog/node_modules/koa-router/lib/router.js:351:31)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at app.use (/Users/spfv/blog/server/server.js:21:9)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at bodyParser (/Users/spfv/blog/node_modules/koa-bodyparser/index.js:86:11)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'token lose' } }
[2018-06-04T16:48:24.701] [ERROR] error - { method: 'POST',
  url: '/api/postArticleContent',
  body: { id: '5b14fcd111fac960d136a71d' },
  costTime: undefined,
  err: 
   { UnauthorizedError: token lose
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at module.exports (/Users/spfv/blog/server/token/checkToken.js:13:14)
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at next (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
       at /Users/spfv/blog/node_modules/koa-router/lib/router.js:346:16
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at /Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
       at dispatch (/Users/spfv/blog/node_modules/koa-router/lib/router.js:351:31)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at app.use (/Users/spfv/blog/server/server.js:21:9)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at bodyParser (/Users/spfv/blog/node_modules/koa-bodyparser/index.js:86:11)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'token lose' } }
[2018-06-05T17:22:53.403] [ERROR] error - { method: 'POST',
  url: '/api/upArticle',
  body: { id: '5b14fcd111fac960d136a71d' },
  costTime: undefined,
  err: 
   TypeError: Uparticle.save is not a function
       at Promise (/Users/spfv/blog/server/info/article.js:112:15)
       at Promise (<anonymous>)
       at upArticle (/Users/spfv/blog/server/info/article.js:111:21)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) }
[2018-06-05T17:29:55.191] [ERROR] error - { method: 'POST',
  url: '/api/upArticle',
  body: { id: '5b14fcd111fac960d136a71d' },
  costTime: undefined,
  err: 
   TypeError: Uparticle.insert is not a function
       at Promise (/Users/spfv/blog/server/info/article.js:112:15)
       at Promise (<anonymous>)
       at upArticle (/Users/spfv/blog/server/info/article.js:111:21)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) }
[2018-06-05T17:30:16.373] [ERROR] error - { method: 'POST',
  url: '/api/upArticle',
  body: { id: '5b14fcd111fac960d136a71d' },
  costTime: undefined,
  err: 
   TypeError: Uparticle.insert is not a function
       at Promise (/Users/spfv/blog/server/info/article.js:112:15)
       at Promise (<anonymous>)
       at upArticle (/Users/spfv/blog/server/info/article.js:111:21)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) }
[2018-06-05T17:30:35.062] [ERROR] error - { method: 'POST',
  url: '/api/upArticle',
  body: { id: '5b14fcd111fac960d136a71d' },
  costTime: undefined,
  err: 
   TypeError: Uparticle.save is not a function
       at Promise (/Users/spfv/blog/server/info/article.js:112:15)
       at Promise (<anonymous>)
       at upArticle (/Users/spfv/blog/server/info/article.js:111:21)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) }
[2018-06-05T17:34:47.418] [ERROR] error - { method: 'POST',
  url: '/api/upArticle',
  body: { id: '5b14fcd111fac960d136a71d' },
  costTime: undefined,
  err: 
   TypeError: Uparticle.save is not a function
       at Promise (/Users/spfv/blog/server/info/article.js:112:15)
       at Promise (<anonymous>)
       at upArticle (/Users/spfv/blog/server/info/article.js:111:21)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) }
[2018-06-05T17:35:15.543] [ERROR] error - { method: 'POST',
  url: '/api/upArticle',
  body: { id: '5b14fcd111fac960d136a71d' },
  costTime: undefined,
  err: 
   { ObjectParameterError: Parameter "filter" to update() must be an object, got 
       at ObjectParameterError (/Users/spfv/blog/node_modules/mongoose/lib/error/objectParameter.js:23:11)
       at _update (/Users/spfv/blog/node_modules/mongoose/lib/query.js:2951:17)
       at model.Query.Query.update (/Users/spfv/blog/node_modules/mongoose/lib/query.js:2760:10)
       at _update (/Users/spfv/blog/node_modules/mongoose/lib/model.js:2626:16)
       at Function.update (/Users/spfv/blog/node_modules/mongoose/lib/model.js:2530:10)
       at Promise (/Users/spfv/blog/server/info/article.js:112:15)
       at Promise (<anonymous>)
       at upArticle (/Users/spfv/blog/server/info/article.js:111:21)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7)
     message: 'Parameter "filter" to update() must be an object, got ',
     name: 'ObjectParameterError' } }
[2018-06-05T17:37:24.402] [ERROR] error - { method: 'POST',
  url: '/api/upArticle',
  body: { id: '5b14fcd111fac960d136a71d' },
  costTime: undefined,
  err: 
   { DocumentNotFoundError: No document found for query "{ _id: 5b14fcd111fac960d136a71d }"
       at DocumentNotFoundError (/Users/spfv/blog/node_modules/mongoose/lib/error/notFound.js:31:11)
       at $__handleSave (/Users/spfv/blog/node_modules/mongoose/lib/model.js:273:17)
       at /Users/spfv/blog/node_modules/mongoose/lib/model.js:210:9
       at result (/Users/spfv/blog/node_modules/mongodb/lib/utils.js:413:17)
       at session.endSession (/Users/spfv/blog/node_modules/mongodb/lib/utils.js:400:11)
       at ClientSession.endSession (/Users/spfv/blog/node_modules/mongodb-core/lib/sessions.js:69:41)
       at executeCallback (/Users/spfv/blog/node_modules/mongodb/lib/utils.js:396:17)
       at handleCallback (/Users/spfv/blog/node_modules/mongodb/lib/utils.js:128:55)
       at /Users/spfv/blog/node_modules/mongodb/lib/collection.js:1037:5
       at /Users/spfv/blog/node_modules/mongodb-core/lib/connection/pool.js:541:18
       at _combinedTickCallback (internal/process/next_tick.js:131:7)
       at process._tickCallback (internal/process/next_tick.js:180:9)
     message: 'No document found for query "{ _id: 5b14fcd111fac960d136a71d }"',
     name: 'DocumentNotFoundError',
     query: { _id: 5b14fcd111fac960d136a71d } } }
[2018-06-05T17:38:37.370] [ERROR] error - { method: 'POST',
  url: '/api/upArticle',
  body: { id: '5b14fcd111fac960d136a71d' },
  costTime: undefined,
  err: 
   { Error
       at MongooseError (/Users/spfv/blog/node_modules/mongoose/lib/error/index.js:12:11)
       at Timeout._onTimeout (/Users/spfv/blog/node_modules/mongoose/lib/model.js:153:18)
       at ontimeout (timers.js:469:11)
       at tryOnTimeout (timers.js:304:5)
       at Timer.listOnTimeout (timers.js:264:5)
     message: 'document must have an _id before saving',
     name: 'MongooseError' } }
[2018-06-05T17:48:31.107] [ERROR] error - { method: 'POST',
  url: '/api/upArticle',
  body: { id: '5b14fcd111fac960d136a71d' },
  costTime: undefined,
  err: 
   { ObjectParameterError: Parameter "obj" to Document() must be an object, got {"creatTime":"2018-06-04 16:48","_id":"5b14fcd111fac960d136a71d","title":"新标题","content":"111111111111111","htmlCode":"<p>111111111111111</p>\n"}
       at ObjectParameterError (/Users/spfv/blog/node_modules/mongoose/lib/error/objectParameter.js:23:11)
       at model.Document (/Users/spfv/blog/node_modules/mongoose/lib/document.js:56:11)
       at model.Model (/Users/spfv/blog/node_modules/mongoose/lib/model.js:60:12)
       at new model (/Users/spfv/blog/node_modules/mongoose/lib/model.js:3757:13)
       at upArticle (/Users/spfv/blog/server/info/article.js:111:16)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7)
     message: 'Parameter "obj" to Document() must be an object, got {"creatTime":"2018-06-04 16:48","_id":"5b14fcd111fac960d136a71d","title":"新标题","content":"111111111111111","htmlCode":"<p>111111111111111</p>\\n"}',
     name: 'ObjectParameterError' } }
[2018-06-05T17:49:24.786] [ERROR] error - { method: 'POST',
  url: '/api/upArticle',
  body: { id: '5b14fcd111fac960d136a71d' },
  costTime: undefined,
  err: 
   SyntaxError: Unexpected token c in JSON at position 2
       at JSON.parse (<anonymous>)
       at upArticle (/Users/spfv/blog/server/info/article.js:113:35)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) }
[2018-06-05T17:49:55.626] [ERROR] error - { method: 'POST',
  url: '/api/upArticle',
  body: { id: '5b14fcd111fac960d136a71d' },
  costTime: undefined,
  err: 
   { ObjectParameterError: Parameter "obj" to Document() must be an object, got {"creatTime":"2018-06-04 16:48","_id":"5b14fcd111fac960d136a71d","title":"新标题","content":"111111111111111","htmlCode":"<p>111111111111111</p>\n"}
       at ObjectParameterError (/Users/spfv/blog/node_modules/mongoose/lib/error/objectParameter.js:23:11)
       at model.Document (/Users/spfv/blog/node_modules/mongoose/lib/document.js:56:11)
       at model.Model (/Users/spfv/blog/node_modules/mongoose/lib/model.js:60:12)
       at new model (/Users/spfv/blog/node_modules/mongoose/lib/model.js:3757:13)
       at upArticle (/Users/spfv/blog/server/info/article.js:113:16)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7)
     message: 'Parameter "obj" to Document() must be an object, got {"creatTime":"2018-06-04 16:48","_id":"5b14fcd111fac960d136a71d","title":"新标题","content":"111111111111111","htmlCode":"<p>111111111111111</p>\\n"}',
     name: 'ObjectParameterError' } }
[2018-06-05T17:51:25.316] [ERROR] error - { method: 'POST',
  url: '/api/upArticle',
  body: { id: '5b14fcd111fac960d136a71d' },
  costTime: undefined,
  err: 
   { ObjectParameterError: Parameter "obj" to Document() must be an object, got {"creatTime":"2018-06-04 16:48","_id":"5b14fcd111fac960d136a71d","title":"新标题","content":"111111111111111","htmlCode":"<p>111111111111111</p>\n"}
       at ObjectParameterError (/Users/spfv/blog/node_modules/mongoose/lib/error/objectParameter.js:23:11)
       at model.Document (/Users/spfv/blog/node_modules/mongoose/lib/document.js:56:11)
       at model.Model (/Users/spfv/blog/node_modules/mongoose/lib/model.js:60:12)
       at new model (/Users/spfv/blog/node_modules/mongoose/lib/model.js:3757:13)
       at upArticle (/Users/spfv/blog/server/info/article.js:113:16)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7)
     message: 'Parameter "obj" to Document() must be an object, got {"creatTime":"2018-06-04 16:48","_id":"5b14fcd111fac960d136a71d","title":"新标题","content":"111111111111111","htmlCode":"<p>111111111111111</p>\\n"}',
     name: 'ObjectParameterError' } }
[2018-06-05T17:56:42.662] [ERROR] error - { method: 'POST',
  url: '/api/upArticle',
  body: { id: '5b14fcd111fac960d136a71d' },
  costTime: undefined,
  err: 
   { ObjectParameterError: Parameter "obj" to Document() must be an object, got function (options) {
     return this.$toObject(options);
   }
       at ObjectParameterError (/Users/spfv/blog/node_modules/mongoose/lib/error/objectParameter.js:23:11)
       at model.Document (/Users/spfv/blog/node_modules/mongoose/lib/document.js:56:11)
       at model.Model (/Users/spfv/blog/node_modules/mongoose/lib/model.js:60:12)
       at new model (/Users/spfv/blog/node_modules/mongoose/lib/model.js:3757:13)
       at upArticle (/Users/spfv/blog/server/info/article.js:113:16)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7)
     message: 'Parameter "obj" to Document() must be an object, got function (options) {\n  return this.$toObject(options);\n}',
     name: 'ObjectParameterError' } }
[2018-06-05T17:57:09.494] [ERROR] error - { method: 'POST',
  url: '/api/upArticle',
  body: { id: '5b14fcd111fac960d136a71d' },
  costTime: undefined,
  err: 
   { ObjectParameterError: Parameter "obj" to Document() must be an object, got function () {
     return inspect(this.inspect());
   }
       at ObjectParameterError (/Users/spfv/blog/node_modules/mongoose/lib/error/objectParameter.js:23:11)
       at model.Document (/Users/spfv/blog/node_modules/mongoose/lib/document.js:56:11)
       at model.Model (/Users/spfv/blog/node_modules/mongoose/lib/model.js:60:12)
       at new model (/Users/spfv/blog/node_modules/mongoose/lib/model.js:3757:13)
       at upArticle (/Users/spfv/blog/server/info/article.js:113:16)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7)
     message: 'Parameter "obj" to Document() must be an object, got function () {\n  return inspect(this.inspect());\n}',
     name: 'ObjectParameterError' } }
[2018-06-05T17:57:49.179] [ERROR] error - { method: 'POST',
  url: '/api/upArticle',
  body: { id: '5b14fcd111fac960d136a71d' },
  costTime: undefined,
  err: 
   { ObjectParameterError: Parameter "obj" to Document() must be an object, got function () {
     return inspect(this.inspect());
   }
       at ObjectParameterError (/Users/spfv/blog/node_modules/mongoose/lib/error/objectParameter.js:23:11)
       at model.Document (/Users/spfv/blog/node_modules/mongoose/lib/document.js:56:11)
       at model.Model (/Users/spfv/blog/node_modules/mongoose/lib/model.js:60:12)
       at new model (/Users/spfv/blog/node_modules/mongoose/lib/model.js:3757:13)
       at upArticle (/Users/spfv/blog/server/info/article.js:113:16)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7)
     message: 'Parameter "obj" to Document() must be an object, got function () {\n  return inspect(this.inspect());\n}',
     name: 'ObjectParameterError' } }
[2018-06-06T09:09:24.168] [ERROR] error - { method: 'POST',
  url: '/api/upArticle',
  body: { id: '5b14fcd111fac960d136a71d' },
  costTime: undefined,
  err: 
   { ObjectParameterError: Parameter "obj" to Document() must be an object, got function toString() { [native code] }
       at ObjectParameterError (/Users/spfv/blog/node_modules/mongoose/lib/error/objectParameter.js:23:11)
       at model.Document (/Users/spfv/blog/node_modules/mongoose/lib/document.js:56:11)
       at model.Model (/Users/spfv/blog/node_modules/mongoose/lib/model.js:60:12)
       at new model (/Users/spfv/blog/node_modules/mongoose/lib/model.js:3757:13)
       at upArticle (/Users/spfv/blog/server/info/article.js:113:16)
       at <anonymous>
     message: 'Parameter "obj" to Document() must be an object, got function toString() { [native code] }',
     name: 'ObjectParameterError' } }
[2018-06-06T09:09:37.899] [ERROR] error - { method: 'POST',
  url: '/api/upArticle',
  body: { id: '5b14fcd111fac960d136a71d' },
  costTime: undefined,
  err: 
   ReferenceError: updata is not defined
       at Promise (/Users/spfv/blog/server/info/article.js:118:5)
       at Promise (<anonymous>)
       at upArticle (/Users/spfv/blog/server/info/article.js:117:21)
       at <anonymous> }
[2018-06-06T09:11:16.054] [ERROR] error - { method: 'POST',
  url: '/api/upArticle',
  body: { id: '5b14fcd111fac960d136a71d' },
  costTime: undefined,
  err: 
   TypeError: data.toJson is not a function
       at upArticle (/Users/spfv/blog/server/info/article.js:112:20)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) }
[2018-06-06T17:48:16.642] [ERROR] error - { method: 'POST',
  url: '/api/upArticle',
  body: { id: '5b14fcd111fac960d136a71d' },
  costTime: undefined,
  err: 
   { MongoError: Performing an update on the path '_id' would modify the immutable field '_id'
       at Function.MongoError.create (/Users/spfv/blog/node_modules/mongodb-core/lib/error.js:45:10)
       at toError (/Users/spfv/blog/node_modules/mongodb/lib/utils.js:149:22)
       at /Users/spfv/blog/node_modules/mongodb/lib/collection.js:1035:39
       at /Users/spfv/blog/node_modules/mongodb-core/lib/connection/pool.js:541:18
       at _combinedTickCallback (internal/process/next_tick.js:131:7)
       at process._tickCallback (internal/process/next_tick.js:180:9)
     name: 'MongoError',
     message: 'Performing an update on the path \'_id\' would modify the immutable field \'_id\'',
     driver: true,
     index: 0,
     code: 66,
     errmsg: 'Performing an update on the path \'_id\' would modify the immutable field \'_id\'' } }
[2018-06-06T17:52:04.495] [ERROR] error - { method: 'POST',
  url: '/api/upArticle',
  body: { id: '5b14fcd111fac960d136a71d' },
  costTime: undefined,
  err: 
   { MongoError: E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId('5b14fcd111fac960d136a71d') }
       at /Users/spfv/blog/node_modules/mongodb/lib/bulk/unordered.js:535:15
       at handleCallback (/Users/spfv/blog/node_modules/mongodb/lib/utils.js:128:55)
       at resultHandler (/Users/spfv/blog/node_modules/mongodb/lib/bulk/unordered.js:456:5)
       at /Users/spfv/blog/node_modules/mongodb-core/lib/connection/pool.js:541:18
       at _combinedTickCallback (internal/process/next_tick.js:131:7)
       at process._tickCallback (internal/process/next_tick.js:180:9)
     name: 'BulkWriteError',
     message: 'E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId(\'5b14fcd111fac960d136a71d\') }',
     driver: true,
     code: 11000,
     index: 0,
     errmsg: 'E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId(\'5b14fcd111fac960d136a71d\') }',
     getOperation: [Function],
     toJSON: [Function],
     toString: [Function],
     result: 
      BulkWriteResult {
        ok: [Getter],
        nInserted: [Getter],
        nUpserted: [Getter],
        nMatched: [Getter],
        nModified: [Getter],
        nRemoved: [Getter],
        getInsertedIds: [Function],
        getUpsertedIds: [Function],
        getUpsertedIdAt: [Function],
        getRawResponse: [Function],
        hasWriteErrors: [Function],
        getWriteErrorCount: [Function],
        getWriteErrorAt: [Function],
        getWriteErrors: [Function],
        getLastOp: [Function],
        getWriteConcernError: [Function],
        toJSON: [Function],
        toString: [Function],
        isOk: [Function] } } }
[2018-06-06T17:52:49.765] [ERROR] error - { method: 'POST',
  url: '/api/upArticle',
  body: { id: '5b14fcd111fac960d136a71d' },
  costTime: undefined,
  err: 
   { MongoError: E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId('5b14fcd111fac960d136a71d') }
       at /Users/spfv/blog/node_modules/mongodb/lib/bulk/unordered.js:535:15
       at handleCallback (/Users/spfv/blog/node_modules/mongodb/lib/utils.js:128:55)
       at resultHandler (/Users/spfv/blog/node_modules/mongodb/lib/bulk/unordered.js:456:5)
       at /Users/spfv/blog/node_modules/mongodb-core/lib/connection/pool.js:541:18
       at _combinedTickCallback (internal/process/next_tick.js:131:7)
       at process._tickCallback (internal/process/next_tick.js:180:9)
     name: 'BulkWriteError',
     message: 'E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId(\'5b14fcd111fac960d136a71d\') }',
     driver: true,
     code: 11000,
     index: 0,
     errmsg: 'E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId(\'5b14fcd111fac960d136a71d\') }',
     getOperation: [Function],
     toJSON: [Function],
     toString: [Function],
     result: 
      BulkWriteResult {
        ok: [Getter],
        nInserted: [Getter],
        nUpserted: [Getter],
        nMatched: [Getter],
        nModified: [Getter],
        nRemoved: [Getter],
        getInsertedIds: [Function],
        getUpsertedIds: [Function],
        getUpsertedIdAt: [Function],
        getRawResponse: [Function],
        hasWriteErrors: [Function],
        getWriteErrorCount: [Function],
        getWriteErrorAt: [Function],
        getWriteErrors: [Function],
        getLastOp: [Function],
        getWriteConcernError: [Function],
        toJSON: [Function],
        toString: [Function],
        isOk: [Function] } } }
[2018-06-07T09:23:08.751] [ERROR] error - { method: 'POST',
  url: '/api/upArticle',
  body: { id: '5b14fcd111fac960d136a71d' },
  costTime: undefined,
  err: 
   { MongoError: E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId('5b14fcd111fac960d136a71d') }
       at /Users/spfv/blog/node_modules/mongodb/lib/bulk/unordered.js:535:15
       at handleCallback (/Users/spfv/blog/node_modules/mongodb/lib/utils.js:128:55)
       at resultHandler (/Users/spfv/blog/node_modules/mongodb/lib/bulk/unordered.js:456:5)
       at /Users/spfv/blog/node_modules/mongodb-core/lib/connection/pool.js:541:18
       at _combinedTickCallback (internal/process/next_tick.js:131:7)
       at process._tickCallback (internal/process/next_tick.js:180:9)
     name: 'BulkWriteError',
     message: 'E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId(\'5b14fcd111fac960d136a71d\') }',
     driver: true,
     code: 11000,
     index: 0,
     errmsg: 'E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId(\'5b14fcd111fac960d136a71d\') }',
     getOperation: [Function],
     toJSON: [Function],
     toString: [Function],
     result: 
      BulkWriteResult {
        ok: [Getter],
        nInserted: [Getter],
        nUpserted: [Getter],
        nMatched: [Getter],
        nModified: [Getter],
        nRemoved: [Getter],
        getInsertedIds: [Function],
        getUpsertedIds: [Function],
        getUpsertedIdAt: [Function],
        getRawResponse: [Function],
        hasWriteErrors: [Function],
        getWriteErrorCount: [Function],
        getWriteErrorAt: [Function],
        getWriteErrors: [Function],
        getLastOp: [Function],
        getWriteConcernError: [Function],
        toJSON: [Function],
        toString: [Function],
        isOk: [Function] } } }
[2018-06-07T09:23:29.817] [ERROR] error - { method: 'POST',
  url: '/api/upArticle',
  body: { id: '5b14fcd111fac960d136a71d' },
  costTime: undefined,
  err: 
   { MongoError: E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId('5b14fcd111fac960d136a71d') }
       at /Users/spfv/blog/node_modules/mongodb/lib/bulk/unordered.js:535:15
       at handleCallback (/Users/spfv/blog/node_modules/mongodb/lib/utils.js:128:55)
       at resultHandler (/Users/spfv/blog/node_modules/mongodb/lib/bulk/unordered.js:456:5)
       at /Users/spfv/blog/node_modules/mongodb-core/lib/connection/pool.js:541:18
       at _combinedTickCallback (internal/process/next_tick.js:131:7)
       at process._tickCallback (internal/process/next_tick.js:180:9)
     name: 'BulkWriteError',
     message: 'E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId(\'5b14fcd111fac960d136a71d\') }',
     driver: true,
     code: 11000,
     index: 0,
     errmsg: 'E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId(\'5b14fcd111fac960d136a71d\') }',
     getOperation: [Function],
     toJSON: [Function],
     toString: [Function],
     result: 
      BulkWriteResult {
        ok: [Getter],
        nInserted: [Getter],
        nUpserted: [Getter],
        nMatched: [Getter],
        nModified: [Getter],
        nRemoved: [Getter],
        getInsertedIds: [Function],
        getUpsertedIds: [Function],
        getUpsertedIdAt: [Function],
        getRawResponse: [Function],
        hasWriteErrors: [Function],
        getWriteErrorCount: [Function],
        getWriteErrorAt: [Function],
        getWriteErrors: [Function],
        getLastOp: [Function],
        getWriteConcernError: [Function],
        toJSON: [Function],
        toString: [Function],
        isOk: [Function] } } }
[2018-06-07T09:23:45.549] [ERROR] error - { method: 'POST',
  url: '/api/upArticle',
  body: { id: '5b14fcd111fac960d136a71d' },
  costTime: undefined,
  err: 
   { MongoError: E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId('5b14fcd111fac960d136a71d') }
       at /Users/spfv/blog/node_modules/mongodb/lib/bulk/unordered.js:535:15
       at handleCallback (/Users/spfv/blog/node_modules/mongodb/lib/utils.js:128:55)
       at resultHandler (/Users/spfv/blog/node_modules/mongodb/lib/bulk/unordered.js:456:5)
       at /Users/spfv/blog/node_modules/mongodb-core/lib/connection/pool.js:541:18
       at _combinedTickCallback (internal/process/next_tick.js:131:7)
       at process._tickCallback (internal/process/next_tick.js:180:9)
     name: 'BulkWriteError',
     message: 'E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId(\'5b14fcd111fac960d136a71d\') }',
     driver: true,
     code: 11000,
     index: 0,
     errmsg: 'E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId(\'5b14fcd111fac960d136a71d\') }',
     getOperation: [Function],
     toJSON: [Function],
     toString: [Function],
     result: 
      BulkWriteResult {
        ok: [Getter],
        nInserted: [Getter],
        nUpserted: [Getter],
        nMatched: [Getter],
        nModified: [Getter],
        nRemoved: [Getter],
        getInsertedIds: [Function],
        getUpsertedIds: [Function],
        getUpsertedIdAt: [Function],
        getRawResponse: [Function],
        hasWriteErrors: [Function],
        getWriteErrorCount: [Function],
        getWriteErrorAt: [Function],
        getWriteErrors: [Function],
        getLastOp: [Function],
        getWriteConcernError: [Function],
        toJSON: [Function],
        toString: [Function],
        isOk: [Function] } } }
[2018-06-07T09:23:48.016] [ERROR] error - { method: 'POST',
  url: '/api/upArticle',
  body: { id: '5b14fcd111fac960d136a71d' },
  costTime: undefined,
  err: 
   { MongoError: E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId('5b14fcd111fac960d136a71d') }
       at /Users/spfv/blog/node_modules/mongodb/lib/bulk/unordered.js:535:15
       at handleCallback (/Users/spfv/blog/node_modules/mongodb/lib/utils.js:128:55)
       at resultHandler (/Users/spfv/blog/node_modules/mongodb/lib/bulk/unordered.js:456:5)
       at /Users/spfv/blog/node_modules/mongodb-core/lib/connection/pool.js:541:18
       at _combinedTickCallback (internal/process/next_tick.js:131:7)
       at process._tickCallback (internal/process/next_tick.js:180:9)
     name: 'BulkWriteError',
     message: 'E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId(\'5b14fcd111fac960d136a71d\') }',
     driver: true,
     code: 11000,
     index: 0,
     errmsg: 'E11000 duplicate key error collection: blog.uparticles index: _id_ dup key: { : ObjectId(\'5b14fcd111fac960d136a71d\') }',
     getOperation: [Function],
     toJSON: [Function],
     toString: [Function],
     result: 
      BulkWriteResult {
        ok: [Getter],
        nInserted: [Getter],
        nUpserted: [Getter],
        nMatched: [Getter],
        nModified: [Getter],
        nRemoved: [Getter],
        getInsertedIds: [Function],
        getUpsertedIds: [Function],
        getUpsertedIdAt: [Function],
        getRawResponse: [Function],
        hasWriteErrors: [Function],
        getWriteErrorCount: [Function],
        getWriteErrorAt: [Function],
        getWriteErrors: [Function],
        getLastOp: [Function],
        getWriteConcernError: [Function],
        toJSON: [Function],
        toString: [Function],
        isOk: [Function] } } }
[2018-06-12T16:25:36.370] [ERROR] error - { method: 'POST',
  url: '/api/ArticleList',
  body: {},
  costTime: undefined,
  err: 
   ReferenceError: show is not defined
       at articleList (/Users/spfv/blog/server/info/article.js:32:5)
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at next (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
       at /Users/spfv/blog/node_modules/koa-router/lib/router.js:346:16
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at /Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
       at dispatch (/Users/spfv/blog/node_modules/koa-router/lib/router.js:351:31)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at app.use (/Users/spfv/blog/server/server.js:21:9)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at bodyParser (/Users/spfv/blog/node_modules/koa-bodyparser/index.js:86:11)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) }
[2018-06-12T16:25:37.197] [ERROR] error - { method: 'POST',
  url: '/api/ArticleList',
  body: {},
  costTime: undefined,
  err: 
   ReferenceError: show is not defined
       at articleList (/Users/spfv/blog/server/info/article.js:32:5)
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at next (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
       at /Users/spfv/blog/node_modules/koa-router/lib/router.js:346:16
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at /Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
       at dispatch (/Users/spfv/blog/node_modules/koa-router/lib/router.js:351:31)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at app.use (/Users/spfv/blog/server/server.js:21:9)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at bodyParser (/Users/spfv/blog/node_modules/koa-bodyparser/index.js:86:11)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) }
[2018-06-12T16:25:37.747] [ERROR] error - { method: 'POST',
  url: '/api/ArticleList',
  body: {},
  costTime: undefined,
  err: 
   ReferenceError: show is not defined
       at articleList (/Users/spfv/blog/server/info/article.js:32:5)
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at next (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
       at /Users/spfv/blog/node_modules/koa-router/lib/router.js:346:16
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at /Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
       at dispatch (/Users/spfv/blog/node_modules/koa-router/lib/router.js:351:31)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at app.use (/Users/spfv/blog/server/server.js:21:9)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at bodyParser (/Users/spfv/blog/node_modules/koa-bodyparser/index.js:86:11)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) }
[2018-06-12T17:09:49.224] [ERROR] error - { method: 'POST',
  url: '/api/upArticle',
  body: { id: '5b1f871f11903c2673e89d23' },
  costTime: undefined,
  err: 
   Error: non-error thrown: {"n":1,"nModified":0,"ok":1}
       at Object.onerror (/Users/spfv/blog/node_modules/koa/lib/context.js:109:40)
       at onerror (/Users/spfv/blog/node_modules/koa/lib/application.js:147:32)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) }
[2018-06-12T17:10:09.168] [ERROR] error - { method: 'POST',
  url: '/api/upArticle',
  body: { id: '5b1f871f11903c2673e89d23' },
  costTime: undefined,
  err: 
   Error: non-error thrown: {"n":1,"nModified":0,"ok":1}
       at Object.onerror (/Users/spfv/blog/node_modules/koa/lib/context.js:109:40)
       at onerror (/Users/spfv/blog/node_modules/koa/lib/application.js:147:32)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) }
[2018-06-15T15:03:06.306] [ERROR] error - { method: 'GET',
  url: '/api/getArticleList',
  body: {},
  costTime: undefined,
  err: 
   { UnauthorizedError: token lose
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at module.exports (/Users/spfv/blog/server/token/checkToken.js:13:14)
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at next (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
       at /Users/spfv/blog/node_modules/koa-router/lib/router.js:346:16
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at /Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
       at dispatch (/Users/spfv/blog/node_modules/koa-router/lib/router.js:351:31)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at app.use (/Users/spfv/blog/server/server.js:21:9)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at bodyParser (/Users/spfv/blog/node_modules/koa-bodyparser/index.js:86:11)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'token lose' } }
[2018-06-26T08:50:07.138] [ERROR] error - { method: 'GET',
  url: '/api/getArticleList',
  body: {},
  costTime: undefined,
  err: 
   { UnauthorizedError: token lose
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at module.exports (/Users/spfv/blog/server/token/checkToken.js:13:14)
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at next (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
       at /Users/spfv/blog/node_modules/koa-router/lib/router.js:346:16
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at /Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
       at dispatch (/Users/spfv/blog/node_modules/koa-router/lib/router.js:351:31)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at app.use (/Users/spfv/blog/server/server.js:21:9)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at bodyParser (/Users/spfv/blog/node_modules/koa-bodyparser/index.js:86:11)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'token lose' } }
[2018-08-14T15:46:45.003] [ERROR] error - { method: 'GET',
  url: '/api/getArticleList',
  body: {},
  costTime: undefined,
  err: 
   { UnauthorizedError: token lose
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at module.exports (/Users/spfv/blog/server/token/checkToken.js:13:14)
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at next (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
       at /Users/spfv/blog/node_modules/koa-router/lib/router.js:346:16
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at /Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
       at dispatch (/Users/spfv/blog/node_modules/koa-router/lib/router.js:351:31)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at app.use (/Users/spfv/blog/server/server.js:21:9)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at bodyParser (/Users/spfv/blog/node_modules/koa-bodyparser/index.js:86:11)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'token lose' } }
[2018-08-14T15:46:47.899] [ERROR] error - { method: 'POST',
  url: '/api/postArticleContent',
  body: { id: '5b7288e78a9f0dc4ae8532bc' },
  costTime: undefined,
  err: 
   { UnauthorizedError: token lose
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at module.exports (/Users/spfv/blog/server/token/checkToken.js:13:14)
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at next (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
       at /Users/spfv/blog/node_modules/koa-router/lib/router.js:346:16
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at /Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
       at dispatch (/Users/spfv/blog/node_modules/koa-router/lib/router.js:351:31)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at app.use (/Users/spfv/blog/server/server.js:21:9)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at bodyParser (/Users/spfv/blog/node_modules/koa-bodyparser/index.js:86:11)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'token lose' } }
[2018-10-18T08:56:21.254] [ERROR] error - { method: 'POST',
  url: '/api/getStatistics',
  body: {},
  costTime: undefined,
  err: 
   { UnauthorizedError: token lose
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at module.exports (/Users/spfv/blog/server/token/checkToken.js:13:14)
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at next (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
       at /Users/spfv/blog/node_modules/koa-router/lib/router.js:346:16
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at /Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
       at dispatch (/Users/spfv/blog/node_modules/koa-router/lib/router.js:351:31)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at app.use (/Users/spfv/blog/server/server.js:21:9)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at bodyParser (/Users/spfv/blog/node_modules/koa-bodyparser/index.js:86:11)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'token lose' } }
[2018-10-18T08:56:33.439] [ERROR] error - { method: 'GET',
  url: '/api/getArticleList',
  body: {},
  costTime: undefined,
  err: 
   { UnauthorizedError: token lose
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at module.exports (/Users/spfv/blog/server/token/checkToken.js:13:14)
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at next (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
       at /Users/spfv/blog/node_modules/koa-router/lib/router.js:346:16
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at /Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
       at dispatch (/Users/spfv/blog/node_modules/koa-router/lib/router.js:351:31)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at app.use (/Users/spfv/blog/server/server.js:21:9)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at bodyParser (/Users/spfv/blog/node_modules/koa-bodyparser/index.js:86:11)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'token lose' } }
[2018-10-18T10:41:14.749] [ERROR] error - { method: 'POST',
  url: '/api/getStatistics',
  body: {},
  costTime: undefined,
  err: 
   { UnauthorizedError: token lose
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at module.exports (/Users/spfv/blog/server/token/checkToken.js:13:14)
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at next (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
       at /Users/spfv/blog/node_modules/koa-router/lib/router.js:346:16
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at /Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
       at dispatch (/Users/spfv/blog/node_modules/koa-router/lib/router.js:351:31)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at app.use (/Users/spfv/blog/server/server.js:21:9)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at bodyParser (/Users/spfv/blog/node_modules/koa-bodyparser/index.js:86:11)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'token lose' } }
[2018-10-18T10:41:17.746] [ERROR] error - { method: 'GET',
  url: '/api/getArticleList',
  body: {},
  costTime: undefined,
  err: 
   { UnauthorizedError: token lose
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at module.exports (/Users/spfv/blog/server/token/checkToken.js:13:14)
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at next (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
       at /Users/spfv/blog/node_modules/koa-router/lib/router.js:346:16
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at /Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
       at dispatch (/Users/spfv/blog/node_modules/koa-router/lib/router.js:351:31)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at app.use (/Users/spfv/blog/server/server.js:21:9)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at bodyParser (/Users/spfv/blog/node_modules/koa-bodyparser/index.js:86:11)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'token lose' } }
[2018-10-18T10:44:57.518] [ERROR] error - { method: 'POST',
  url: '/api/getStatistics',
  body: {},
  costTime: undefined,
  err: 
   { UnauthorizedError: token lose
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at module.exports (/Users/spfv/blog/server/token/checkToken.js:13:14)
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at next (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
       at /Users/spfv/blog/node_modules/koa-router/lib/router.js:346:16
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at /Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
       at dispatch (/Users/spfv/blog/node_modules/koa-router/lib/router.js:351:31)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at app.use (/Users/spfv/blog/server/server.js:21:9)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at bodyParser (/Users/spfv/blog/node_modules/koa-bodyparser/index.js:86:11)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'token lose' } }
[2018-10-18T10:45:00.983] [ERROR] error - { method: 'GET',
  url: '/api/getArticleList',
  body: {},
  costTime: undefined,
  err: 
   { UnauthorizedError: token lose
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at module.exports (/Users/spfv/blog/server/token/checkToken.js:13:14)
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at next (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
       at /Users/spfv/blog/node_modules/koa-router/lib/router.js:346:16
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at /Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
       at dispatch (/Users/spfv/blog/node_modules/koa-router/lib/router.js:351:31)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at app.use (/Users/spfv/blog/server/server.js:21:9)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at bodyParser (/Users/spfv/blog/node_modules/koa-bodyparser/index.js:86:11)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'token lose' } }
[2018-10-18T11:01:26.033] [ERROR] error - { method: 'POST',
  url: '/api/getStatistics',
  body: {},
  costTime: undefined,
  err: 
   { UnauthorizedError: token lose
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at module.exports (/Users/spfv/blog/server/token/checkToken.js:13:14)
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at next (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
       at /Users/spfv/blog/node_modules/koa-router/lib/router.js:346:16
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at /Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
       at dispatch (/Users/spfv/blog/node_modules/koa-router/lib/router.js:351:31)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at app.use (/Users/spfv/blog/server/server.js:21:9)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at bodyParser (/Users/spfv/blog/node_modules/koa-bodyparser/index.js:86:11)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'token lose' } }
[2019-02-14T14:28:34.485] [ERROR] error - { method: 'GET',
  url: '/api/getArticleList',
  body: {},
  costTime: undefined,
  err: 
   { UnauthorizedError: token lose
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at module.exports (/Users/spfv/blog/server/token/checkToken.js:13:14)
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at next (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
       at /Users/spfv/blog/node_modules/koa-router/lib/router.js:346:16
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at /Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
       at dispatch (/Users/spfv/blog/node_modules/koa-router/lib/router.js:351:31)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at app.use (/Users/spfv/blog/server/server.js:21:9)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at bodyParser (/Users/spfv/blog/node_modules/koa-bodyparser/index.js:86:11)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'token lose' } }
[2019-02-14T14:30:19.879] [ERROR] error - { method: 'GET',
  url: '/api/getArticleList',
  body: {},
  costTime: undefined,
  err: 
   { UnauthorizedError: token lose
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at module.exports (/Users/spfv/blog/server/token/checkToken.js:13:14)
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at next (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
       at /Users/spfv/blog/node_modules/koa-router/lib/router.js:346:16
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at /Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
       at dispatch (/Users/spfv/blog/node_modules/koa-router/lib/router.js:351:31)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at app.use (/Users/spfv/blog/server/server.js:21:9)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at bodyParser (/Users/spfv/blog/node_modules/koa-bodyparser/index.js:86:11)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'token lose' } }
[2019-02-14T14:30:44.213] [ERROR] error - { method: 'POST',
  url: '/api/postArticleContent',
  body: { id: '5c650b05704c4eb3957b92c7' },
  costTime: undefined,
  err: 
   { UnauthorizedError: token lose
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at module.exports (/Users/spfv/blog/server/token/checkToken.js:13:14)
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at next (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
       at /Users/spfv/blog/node_modules/koa-router/lib/router.js:346:16
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at /Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
       at dispatch (/Users/spfv/blog/node_modules/koa-router/lib/router.js:351:31)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at app.use (/Users/spfv/blog/server/server.js:21:9)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at bodyParser (/Users/spfv/blog/node_modules/koa-bodyparser/index.js:86:11)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'token lose' } }
[2019-02-14T14:30:54.533] [ERROR] error - { method: 'POST',
  url: '/api/postArticleContent',
  body: { id: '5c650b15704c4eb3957b92c8' },
  costTime: undefined,
  err: 
   { UnauthorizedError: token lose
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at module.exports (/Users/spfv/blog/server/token/checkToken.js:13:14)
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at next (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
       at /Users/spfv/blog/node_modules/koa-router/lib/router.js:346:16
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at /Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
       at dispatch (/Users/spfv/blog/node_modules/koa-router/lib/router.js:351:31)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at app.use (/Users/spfv/blog/server/server.js:21:9)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at bodyParser (/Users/spfv/blog/node_modules/koa-bodyparser/index.js:86:11)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'token lose' } }
[2019-02-14T14:30:55.669] [ERROR] error - { method: 'POST',
  url: '/api/postArticleContent',
  body: { id: '5c650b05704c4eb3957b92c7' },
  costTime: undefined,
  err: 
   { UnauthorizedError: token lose
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at module.exports (/Users/spfv/blog/server/token/checkToken.js:13:14)
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at next (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
       at /Users/spfv/blog/node_modules/koa-router/lib/router.js:346:16
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at /Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
       at dispatch (/Users/spfv/blog/node_modules/koa-router/lib/router.js:351:31)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at app.use (/Users/spfv/blog/server/server.js:21:9)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at bodyParser (/Users/spfv/blog/node_modules/koa-bodyparser/index.js:86:11)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'token lose' } }
[2019-02-14T14:30:56.159] [ERROR] error - { method: 'POST',
  url: '/api/postArticleContent',
  body: { id: '5c650b15704c4eb3957b92c8' },
  costTime: undefined,
  err: 
   { UnauthorizedError: token lose
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at module.exports (/Users/spfv/blog/server/token/checkToken.js:13:14)
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at next (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
       at /Users/spfv/blog/node_modules/koa-router/lib/router.js:346:16
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at /Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
       at dispatch (/Users/spfv/blog/node_modules/koa-router/lib/router.js:351:31)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at app.use (/Users/spfv/blog/server/server.js:21:9)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at bodyParser (/Users/spfv/blog/node_modules/koa-bodyparser/index.js:86:11)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'token lose' } }
[2019-02-14T14:31:47.859] [ERROR] error - { method: 'GET',
  url: '/api/getArticleList',
  body: {},
  costTime: undefined,
  err: 
   { UnauthorizedError: token lose
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at module.exports (/Users/spfv/blog/server/token/checkToken.js:13:14)
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at next (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
       at /Users/spfv/blog/node_modules/koa-router/lib/router.js:346:16
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at /Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
       at dispatch (/Users/spfv/blog/node_modules/koa-router/lib/router.js:351:31)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at app.use (/Users/spfv/blog/server/server.js:21:9)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at bodyParser (/Users/spfv/blog/node_modules/koa-bodyparser/index.js:86:11)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'token lose' } }
[2019-02-14T14:34:52.511] [ERROR] error - { method: 'GET',
  url: '/api/getArticleList',
  body: {},
  costTime: undefined,
  err: 
   { UnauthorizedError: token lose
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at module.exports (/Users/spfv/blog/server/token/checkToken.js:13:14)
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at next (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
       at /Users/spfv/blog/node_modules/koa-router/lib/router.js:346:16
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at /Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
       at dispatch (/Users/spfv/blog/node_modules/koa-router/lib/router.js:351:31)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at app.use (/Users/spfv/blog/server/server.js:21:9)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at bodyParser (/Users/spfv/blog/node_modules/koa-bodyparser/index.js:86:11)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'token lose' } }
[2019-02-14T14:36:34.182] [ERROR] error - { method: 'GET',
  url: '/api/getArticleList',
  body: {},
  costTime: undefined,
  err: 
   Error: non-error thrown: "no token in headers"
       at Object.onerror (/Users/spfv/blog/node_modules/koa/lib/context.js:109:40)
       at onerror (/Users/spfv/blog/node_modules/koa/lib/application.js:147:32)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) }
[2019-02-14T14:36:36.443] [ERROR] error - { method: 'GET',
  url: '/api/getArticleList',
  body: {},
  costTime: undefined,
  err: 
   Error: non-error thrown: "no token in headers"
       at Object.onerror (/Users/spfv/blog/node_modules/koa/lib/context.js:109:40)
       at onerror (/Users/spfv/blog/node_modules/koa/lib/application.js:147:32)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) }
[2019-02-14T14:36:37.932] [ERROR] error - { method: 'GET',
  url: '/api/getArticleList',
  body: {},
  costTime: undefined,
  err: 
   Error: non-error thrown: "no token in headers"
       at Object.onerror (/Users/spfv/blog/node_modules/koa/lib/context.js:109:40)
       at onerror (/Users/spfv/blog/node_modules/koa/lib/application.js:147:32)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) }
[2019-02-14T14:37:56.056] [ERROR] error - { method: 'GET',
  url: '/api/getArticleList',
  body: {},
  costTime: undefined,
  err: 
   { UnauthorizedError: token lose
       at Object.throw (/Users/spfv/blog/node_modules/koa/lib/context.js:93:11)
       at module.exports (/Users/spfv/blog/server/token/checkToken.js:13:14)
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at next (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
       at /Users/spfv/blog/node_modules/koa-router/lib/router.js:346:16
       at dispatch (/Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
       at /Users/spfv/blog/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
       at dispatch (/Users/spfv/blog/node_modules/koa-router/lib/router.js:351:31)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at app.use (/Users/spfv/blog/server/server.js:21:9)
       at dispatch (/Users/spfv/blog/node_modules/koa-compose/index.js:42:32)
       at next (/Users/spfv/blog/node_modules/koa-compose/index.js:43:18)
       at bodyParser (/Users/spfv/blog/node_modules/koa-bodyparser/index.js:86:11)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7) message: 'token lose' } }
